# Site settings
# These are used to personalize your new site.
title: Brayden M. Kirkland # your name here
logo: "/images/IMG_7735.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Applied Computing (class of 2026)
  <br /><br />
  <a href="https://example.com/resume">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
repository: "BCoder3/Bcoder3.github.io"
github_username:  BCoder3 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

